import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from core.logger import log


def generate_briefing_card(pulse_data: dict, booking_context: dict) -> dict:
    """Build an advisor briefing card from pulse + booking data."""
    themes = pulse_data.get("themes", [])[:3]
    quotes = pulse_data.get("quotes", [])[:3]
    actions = pulse_data.get("actions", [])[:3]
    booking_code = booking_context.get("booking_code", "N/A")
    topic = booking_context.get("topic", "General")

    card = {
        "booking_code": booking_code,
        "topic": topic,
        "top_themes": [{"name": t.get("theme", ""), "count": t.get("count", 0), "trend": t.get("trend", {}).get("direction", "flat")} for t in themes],
        "sentiment_shift": "declining" if any(t.get("trend", {}).get("direction") == "up" and t.get("count", 0) > 20 for t in themes) else "stable",
        "pain_points": [t.get("theme", "") for t in themes[:2]],
        "talking_points": [
            f"Users are reporting {themes[0].get('theme', 'issues')}" if themes else "Review general feedback",
            f"Consider addressing {themes[1].get('theme', 'concerns')}" if len(themes) > 1 else "Check recent app updates",
            f"Action item: {actions[0]}" if actions else "Review team priorities"
        ],
        "user_quotes": quotes
    }

    log.info("briefing_card: generated for booking {}", booking_code)
    return card


def format_briefing_html(card: dict) -> str:
    """Format briefing card as HTML for email."""
    themes_html = "".join(
        f"<li><strong>{t['name']}</strong> ({t['count']} mentions, trending {t['trend']})</li>"
        for t in card.get("top_themes", [])
    )
    quotes_html = "".join(f"<li><em>\"{q}\"</em></li>" for q in card.get("user_quotes", []))
    points_html = "".join(f"<li>{p}</li>" for p in card.get("talking_points", []))

    return f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <h2>Advisor Briefing Card</h2>
        <p><strong>Booking Code:</strong> {card['booking_code']}</p>
        <p><strong>Topic:</strong> {card['topic']}</p>
        <p><strong>Sentiment:</strong> {card.get('sentiment_shift', 'stable')}</p>
        <h3>Top Customer Themes</h3>
        <ul>{themes_html}</ul>
        <h3>Recent User Voices</h3>
        <ul>{quotes_html}</ul>
        <h3>Suggested Talking Points</h3>
        <ul>{points_html}</ul>
        <hr>
        <p style="color: #666; font-size: 12px;">Generated by INDmoney Investor Ops Suite</p>
    </div>
    """


def format_briefing_plain(card: dict) -> str:
    """Format briefing card as plain text for email fallback."""
    lines = [
        f"ADVISOR BRIEFING CARD",
        f"Booking Code: {card['booking_code']}",
        f"Topic: {card['topic']}",
        f"Sentiment: {card.get('sentiment_shift', 'stable')}",
        "",
        "TOP CUSTOMER THEMES:",
    ]
    for t in card.get("top_themes", []):
        lines.append(f"  - {t['name']} ({t['count']} mentions, {t['trend']})")
    lines.append("")
    lines.append("USER QUOTES:")
    for q in card.get("user_quotes", []):
        lines.append(f'  - "{q}"')
    lines.append("")
    lines.append("TALKING POINTS:")
    for p in card.get("talking_points", []):
        lines.append(f"  - {p}")
    return "\n".join(lines)
