import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from core.logger import log


def generate_briefing_card(pulse_data: dict, booking_context: dict) -> dict:
    """Build an advisor briefing card from pulse + booking data."""
    themes = pulse_data.get("themes", [])[:3]
    quotes = pulse_data.get("quotes", [])[:3]
    actions = pulse_data.get("actions", [])[:3]
    date_range = pulse_data.get("date_range", ["N/A", "N/A"])
    total_reviews = pulse_data.get("total_reviews", 0)

    trend_summary = []
    for t in themes[:3]:
        direction = t.get("trend", {}).get("direction", "flat")
        arrow = "↑" if direction == "up" else "↓" if direction == "down" else "→"
        pct = t.get("trend", {}).get("pct_delta", 0)
        trend_summary.append(f"{arrow} {t['theme']} ({pct:+.0f}%)")

    market_context = {
        "period": f"{date_range[0]} to {date_range[1]}",
        "total_reviews": total_reviews,
        "top_concerns": [t.get("theme", "") for t in themes],
        "trend_summary": ", ".join(trend_summary),
        "sentiment": "declining" if any(
            t.get("trend", {}).get("direction") == "up" and t.get("count", 0) > 30
            for t in themes
        ) else "stable",
    }

    card = {
        "booking_code": booking_context.get("booking_code", "N/A"),
        "topic": booking_context.get("topic", "General"),
        "market_context": market_context,
        "top_themes": [
            {
                "name": t.get("theme", ""),
                "count": t.get("count", 0),
                "trend": t.get("trend", {}).get("direction", "flat"),
            }
            for t in themes
        ],
        "sentiment_shift": market_context["sentiment"],
        "pain_points": [t.get("theme", "") for t in themes[:2]],
        "talking_points": [
            f"Users are reporting {themes[0].get('theme', 'issues')}" if themes else "Review general feedback",
            f"Consider addressing {themes[1].get('theme', 'concerns')}" if len(themes) > 1 else "Check recent app updates",
            f"Action item: {actions[0]}" if actions else "Review team priorities",
        ],
        "user_quotes": quotes,
    }

    log.info("briefing_card: generated for booking {}", booking_context.get("booking_code", "N/A"))
    return card


def format_briefing_html(card: dict) -> str:
    """Format briefing card as HTML for email."""
    mc = card.get("market_context", {})
    market_html = f"""
    <div style="background: #FFF9E6; border-left: 4px solid #D4A437; padding: 16px; margin-bottom: 20px; border-radius: 8px;">
        <h3 style="color: #0B1F3A; margin-top: 0;">&#x1F4CA; Market Context (Customer Sentiment)</h3>
        <p><strong>Period:</strong> {mc.get('period', 'N/A')}</p>
        <p><strong>Reviews Analyzed:</strong> {mc.get('total_reviews', 0)}</p>
        <p><strong>Overall Sentiment:</strong> {mc.get('sentiment', 'stable').upper()}</p>
        <p><strong>Trending Issues:</strong> {mc.get('trend_summary', 'N/A')}</p>
        <p style="margin-bottom: 0;"><strong>Top Customer Concerns:</strong> {', '.join(mc.get('top_concerns', []))}</p>
    </div>
    """

    themes_html = "".join(
        f"<li><strong>{t['name']}</strong> ({t['count']} mentions, trending {t['trend']})</li>"
        for t in card.get("top_themes", [])
    )
    quotes_html = "".join(f"<li><em>\"{q}\"</em></li>" for q in card.get("user_quotes", []))
    points_html = "".join(f"<li>{p}</li>" for p in card.get("talking_points", []))

    return f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <h2 style="color: #0B1F3A;">Advisor Briefing Card</h2>
        <p><strong>Booking Code:</strong> {card['booking_code']}</p>
        <p><strong>Topic:</strong> {card['topic']}</p>

        {market_html}

        <h3 style="color: #0B1F3A;">Top Customer Themes</h3>
        <ul>{themes_html}</ul>

        <h3 style="color: #0B1F3A;">Recent User Voices</h3>
        <ul>{quotes_html}</ul>

        <h3 style="color: #0B1F3A;">Suggested Talking Points</h3>
        <ul>{points_html}</ul>

        <hr style="border: 1px solid #E8EDF3; margin: 20px 0;">
        <p style="color: #666; font-size: 12px;">Generated by INDmoney Investor Ops Suite</p>
    </div>
    """


def format_briefing_plain(card: dict) -> str:
    """Format briefing card as plain text for email fallback."""
    mc = card.get("market_context", {})

    lines = [
        "=" * 60,
        "ADVISOR BRIEFING CARD",
        "=" * 60,
        f"Booking Code: {card['booking_code']}",
        f"Topic: {card['topic']}",
        "",
        "MARKET CONTEXT (CUSTOMER SENTIMENT)",
        "-" * 60,
        f"Period: {mc.get('period', 'N/A')}",
        f"Reviews Analyzed: {mc.get('total_reviews', 0)}",
        f"Overall Sentiment: {mc.get('sentiment', 'stable').upper()}",
        f"Trending Issues: {mc.get('trend_summary', 'N/A')}",
        f"Top Concerns: {', '.join(mc.get('top_concerns', []))}",
        "",
        "TOP CUSTOMER THEMES:",
    ]
    for t in card.get("top_themes", []):
        lines.append(f"  - {t['name']} ({t['count']} mentions, {t['trend']})")
    lines.append("")
    lines.append("USER QUOTES:")
    for q in card.get("user_quotes", []):
        lines.append(f'  - "{q}"')
    lines.append("")
    lines.append("TALKING POINTS:")
    for p in card.get("talking_points", []):
        lines.append(f"  - {p}")
    lines.append("=" * 60)
    return "\n".join(lines)
